
filegroup(
    name = "raw_data",
    srcs = glob([
        "*.bw",
        "*.rgb",
        "*.yuv",
        "*.pgm",
        "*.xml"
    ]),
    visibility = ["//visibility:public"],
)

filegroup(
    name = "models",
    srcs = glob([
        "*.onnx",
        "*.tflite",
        "*.pte"
    ]),
    visibility = ["//visibility:public"],
)