// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbUvhvZ35BO22YW_HsnZroTY9cpeicW2o',
    appId: '1:548317788995:web:5c7568a1a8cccb7fe00df6',
    messagingSenderId: '548317788995',
    projectId: 'ui-proj-a684b',
    authDomain: 'ui-proj-a684b.firebaseapp.com',
    storageBucket: 'ui-proj-a684b.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4nbf2BM_Nzj86WjXxyIQwOztoB-_ufBI',
    appId: '1:548317788995:ios:91bde8a7b93af4c7e00df6',
    messagingSenderId: '548317788995',
    projectId: 'ui-proj-a684b',
    storageBucket: 'ui-proj-a684b.firebasestorage.app',
    iosBundleId: 'com.example.ui',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbUvhvZ35BO22YW_HsnZroTY9cpeicW2o',
    appId: '1:548317788995:web:b248d7f6143fbfe1e00df6',
    messagingSenderId: '548317788995',
    projectId: 'ui-proj-a684b',
    authDomain: 'ui-proj-a684b.firebaseapp.com',
    storageBucket: 'ui-proj-a684b.firebasestorage.app',
  );
}
