cc_test(
    name = "test_array",
    srcs = [
        "test_array.cpp"
    ],
    deps = [
        "//:corevx",
        "@googletest//:gtest_main",
        "//targets/c_model:imported_openvx_c_model",
        "//targets/debug:imported_openvx_debug",
        "//targets/extras:imported_openvx_extras",
        "//targets/opencl:imported_openvx_opencl",
    ],
    size = "small"
)

cc_test(
    name = "test_circular_queue",
    srcs = [
        "test_circular_queue.cpp",
    ],
    deps = [
        "//:corevx",
        "@googletest//:gtest_main",
    ],
    size = "small"
)

cc_test(
    name = "test_context",
    srcs = [
        "test_context.cpp"
    ],
    deps = [
        "//:corevx",
        "@googletest//:gtest_main",
        "//targets/c_model:imported_openvx_c_model",
        "//targets/debug:imported_openvx_debug",
        "//targets/extras:imported_openvx_extras",
        "//targets/opencl:imported_openvx_opencl",
    ],
    size = "small"
)

cc_test(
    name = "test_delay",
    srcs = [
        "test_delay.cpp"
    ],
    deps = [
        "//:corevx",
        "@googletest//:gtest_main",
        "//targets/c_model:imported_openvx_c_model",
        "//targets/debug:imported_openvx_debug",
        "//targets/extras:imported_openvx_extras",
        "//targets/opencl:imported_openvx_opencl",
    ],
    size = "small"
)

cc_test(
    name = "test_distribution",
    srcs = [
        "test_distribution.cpp"
    ],
    deps = [
        "//:corevx",
        "@googletest//:gtest_main",
        "//targets/c_model:imported_openvx_c_model",
        "//targets/debug:imported_openvx_debug",
        "//targets/extras:imported_openvx_extras",
        "//targets/opencl:imported_openvx_opencl",
    ],
    size = "small"
)

cc_test(
    name = "test_dot",
    srcs = [
        "test_dot.cpp"
    ],
    deps = [
        "//:corevx",
        "@googletest//:gtest_main",
        "//targets/c_model:imported_openvx_c_model",
        "//targets/debug:imported_openvx_debug",
        "//targets/extras:imported_openvx_extras",
        "//targets/opencl:imported_openvx_opencl",
    ],
    size = "small"
)

cc_test(
    name = "test_error",
    srcs = [
        "test_error.cpp"
    ],
    deps = [
        "//:corevx",
        "@googletest//:gtest_main",
        "//targets/c_model:imported_openvx_c_model",
        "//targets/debug:imported_openvx_debug",
        "//targets/extras:imported_openvx_extras",
        "//targets/opencl:imported_openvx_opencl",
    ],
    size = "small"
)

cc_test(
    name = "test_image",
    srcs = [
        "test_image.cpp"
    ],
    deps = [
        "//:corevx",
        "@googletest//:gtest_main",
        "//targets/c_model:imported_openvx_c_model",
        "//targets/debug:imported_openvx_debug",
        "//targets/extras:imported_openvx_extras",
        "//targets/opencl:imported_openvx_opencl",
    ],
    size = "small"
)

cc_test(
    name = "test_import",
    srcs = [
        "test_import.cpp"
    ],
    deps = [
        "//:corevx",
        "@googletest//:gtest_main",
        "//targets/c_model:imported_openvx_c_model",
        "//targets/debug:imported_openvx_debug",
        "//targets/extras:imported_openvx_extras",
        "//targets/opencl:imported_openvx_opencl",
    ],
    size = "small"
)

cc_test(
    name = "test_parameter",
    srcs = [
        "test_parameter.cpp"
    ],
    deps = [
        "//:corevx",
        "@googletest//:gtest_main",
        "//targets/c_model:imported_openvx_c_model",
        "//targets/debug:imported_openvx_debug",
        "//targets/extras:imported_openvx_extras",
        "//targets/opencl:imported_openvx_opencl",
    ],
    size = "small"
)

cc_test(
    name = "test_remap",
    srcs = [
        "test_remap.cpp"
    ],
    deps = [
        "//:corevx",
        "@googletest//:gtest_main",
        "//targets/c_model:imported_openvx_c_model",
        "//targets/debug:imported_openvx_debug",
        "//targets/extras:imported_openvx_extras",
        "//targets/opencl:imported_openvx_opencl",
    ],
    size = "small"
)

cc_test(
    name = "test_scalar",
    srcs = [
        "test_scalar.cpp"
    ],
    deps = [
        "//:corevx",
        "@googletest//:gtest_main",
        "//targets/c_model:imported_openvx_c_model",
        "//targets/debug:imported_openvx_debug",
        "//targets/extras:imported_openvx_extras",
        "//targets/opencl:imported_openvx_opencl",
    ],
    size = "small"
)

cc_test(
    name = "test_target",
    srcs = [
        "test_target.cpp"
    ],
    deps = [
        "//:corevx",
        "@googletest//:gtest_main",
        "//targets/c_model:imported_openvx_c_model",
        "//targets/debug:imported_openvx_debug",
        "//targets/extras:imported_openvx_extras",
        "//targets/opencl:imported_openvx_opencl",
    ],
    size = "small"
)

cc_test(
    name = "test_threshold",
    srcs = [
        "test_threshold.cpp"
    ],
    deps = [
        "//:corevx",
        "@googletest//:gtest_main",
        "//targets/c_model:imported_openvx_c_model",
        "//targets/debug:imported_openvx_debug",
        "//targets/extras:imported_openvx_extras",
        "//targets/opencl:imported_openvx_opencl",
    ],
    size = "small"
)

cc_test(
    name = "test_userdataobject",
    srcs = [
        "test_userdataobject.cpp"
    ],
    deps = [
        "//:corevx",
        "@googletest//:gtest_main",
        "//targets/c_model:imported_openvx_c_model",
        "//targets/debug:imported_openvx_debug",
        "//targets/extras:imported_openvx_extras",
        "//targets/opencl:imported_openvx_opencl",
    ],
    size = "small"
)