name: Static Analysis

on:
  push:
    branches: [main]
  pull_request:

jobs:
  cppcheck:
    name: Run Cppcheck
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true
          lfs: true

      - name: Install cppcheck
        run: |
          sudo apt-get update
          sudo apt-get install -y cppcheck

      - name: Run cppcheck
        run: |
          mkdir -p cppcheck-report
          cppcheck --enable=all --inconclusive --quiet \
                   --output-file=cppcheck-report/cppcheck.txt \
                   $GITHUB_WORKSPACE/framework/src/ \
                   -I $GITHUB_WORKSPACE/include/ \
                   -I $GITHUB_WORKSPACE/framework/include/
          cat cppcheck-report/cppcheck.txt

      - name: Upload cppcheck report artifact
        uses: actions/upload-artifact@v4
        with:
          name: cppcheck-report
          path: cppcheck-report/cppcheck.txt
