name: UI CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.29.2'
        channel: 'stable'
        cache: true

    - name: Install dependencies
      run: |
        cd ui
        flutter pub get

    - name: Verify formatting
      run: |
        cd ui
        dart format --set-exit-if-changed .

    - name: Analyze project source
      run: |
        cd ui
        flutter analyze

    - name: Run tests
      run: |
        cd ui
        flutter test --coverage

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        directory: ui/coverage/lcov.info
        fail_ci_if_error: true