name: UI CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.29.2'
        channel: 'stable'
        cache: true

    - name: Install dependencies
      run: |
        cd ui
        sudo apt-get update
        sudo apt-get install -y lcov libgtk-3-dev libblkid-dev liblzma-dev
        flutter pub get

    - name: Verify formatting
      run: |
        cd ui
        dart format --set-exit-if-changed .

    - name: Analyze project source
      run: |
        cd ui
        flutter analyze

    - name: Build linux
      run: |
        cd ui
        flutter build linux

    - name: Build web
      run: |
        cd ui
        flutter build web

    - name: Run tests with coverage
      run: |
        cd ui
        flutter test --coverage
        genhtml coverage/lcov.info -o coverage/html

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: ui/coverage/lcov.info
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true